name: Create Docker Image

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Build docker image
              run: docker build -t frontend-technical:latest .

            - name: Build docker container
              run: docker run -d -p 3000:3000 frontend-technical
